[package]
name = "versioned-binary-serialization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3"
displaydoc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.4"
snafu = { version = "0.7", features = ["backtraces"] }
